### ISSUE TITLE
New Statement Page

### ISSUE THREAD

**Issue by blamarque** [MyResonance/tickets#127]
Need a page with all the tokens transaction

**Comment by Pierre-Oscar** [comment]
![test tokken feed central](https://user-images.githubusercontent.com/81171402/119148901-405cbe00-ba4d-11eb-906d-37b06b1d0124.PNG)
pour garder l'idée que tu en as et rajouter la gauche et la droite

**Comment by Pierre-Oscar** [comment]
![tokken](https://user-images.githubusercontent.com/81171402/119152566-b6165900-ba50-11eb-8bbf-3cbee218c353.PNG)
sans les fonds
