### ISSUE TITLE
Number of workouts in the Pushup challenge

### ISSUE THREAD

**Issue by SchalkCloete** [MyResonance/tickets#134]
When the number of workouts is given for the pushup challenge, it appears to give the total number of pushups completed and not the number of workout sessions:
![image](https://user-images.githubusercontent.com/69623855/120914353-1c7cb780-c69e-11eb-8b8e-af707ada656a.png)
Either replace the "workout(s)" with "pushups" or report the actual number of workouts.

**Comment by blamarque** [comment]
Should br fixed
