### ISSUE TITLE
Pushup camera

### ISSUE THREAD

**Issue by SchalkCloete** [MyResonance/tickets#136]
The mobile camera used in the pushup challenge (probably other challenges as well) could still use a couple of upgrades:

- The picture is strongly zoomed in, making it hard to capture a decent composition
- It would be great if one could preview a photo and replace it with a new one if it's not as nice as you want
- It's currently not possible to write any text above the photo taken directly after the pushup challenge

**Comment by blamarque** [comment]
_The picture is strongly zoomed in, making it hard to capture a decent composition:_
Please provide a example thanks

**Comment by SchalkCloete** [comment]
Hi, here is an example where I tried to get in my whole face and quite a lot of the background. My (rather long) arm was stretched to the max to capture this much background and most of my face.
![image](https://user-images.githubusercontent.com/69623855/120921756-7349b780-c6c5-11eb-99a9-52fa8052dff5.png)
From comparing to zoomed pictures with my regular camera, I estimate it applies a 3-4x zoom.

**Comment by blamarque** [comment]
Hello, 

Can you have a look at version 0.35.12 and let me know if the issue is solve?

**Comment by SchalkCloete** [comment]
Much better now, thanks! It still doesn't seem possible to write in the post directly after taking the photo, but that's at least easy to do by editing directly after it is posted.
