### ISSUE TITLE
More intuitive formatting in the admin post

### ISSUE THREAD

**Issue by SchalkCloete** [MyResonance/tickets#139]
In the few admin posts I did so far, it has been quite challenging to get the formatting right. The post that appears publicly has substantially larger line breaks and sometimes adds extra line breaks. I've also once had the experience that one of the lines I typed in a list simply did not appear in the public post. The differences between the way the post looks in the admin panel and the public version should be much smaller.

**Comment by blamarque** [comment]
Hello,

Does the same happen with post from an activity or main feed page ?
Do you have an example of the line breaks issue ?
Thanks

**Comment by blamarque** [comment]
Hello,

I am happy to say that we review this and added a more transparent way to format using markdown https://www.markdownguide.org/basic-syntax/ 

If you follow the guide for line break (2 space and return at the end of the line) - that should work fine

**Comment by SchalkCloete** [comment]
OK, thanks. I tested it and it works fine if I know about the 2-space-and-Enter trick. However, if you did not tell me this explicitly, I would have found it very confusing that there would be no line break in the actual post if I make a conventional line break with Enter (without extra spaces) in the editor. I guess the trick is to get everyone fully informed. Otherwise, getting a fully intuitive solution where the published post actually looks like it looks in the editor is certainly the best.
