### ISSUE TITLE
More clarity about project or cause on a challenge page

### ISSUE THREAD

**Issue by SchalkCloete** [MyResonance/tickets#140]
I'm confused by this message to the right of the page when viewing a challenge on PC:
![image](https://user-images.githubusercontent.com/69623855/122517231-1082e500-d010-11eb-9395-7e79da9c1c9c.png)
First, "project" is misspelled. 
Second, what is a project and how does it differ from a cause?
Third, why doesn't it just display the causes linked to the community like on the main community page?

**Comment by blamarque** [comment]
I can t believe that we did not see the typo.......
Thanks for reporting it.

Regarding the causes - we needed to highlight a cause to specific experience.
Example with the ocean picture challenge https://app.myresonance.io/activity/56a06d8821b60d171f251853fe714a4d33f69fdf there is a direct correlation with the causes supported here.

I will make sure that if no causes are linked to an experience the message does not appears.

If you want to highlight a cause with an experience, let me know - this process is currently manual.
