### ISSUE TITLE
Bio going out of the box in the Network page

### ISSUE THREAD

**Issue by SchalkCloete** [MyResonance/tickets#22]
Hi, it seems like if you make a little longer bio in the new profile, it goes out of the box in the Network page. It would be good to have longer bios automatically truncated after a certain number of characters followed by (...) so that it looks neater.

**Comment by SchalkCloete** [comment]
I don't see that this is fixed. My bio still goes out of the box on the network page.

**Comment by blamarque** [comment]
Looks ok to me - could you clarify the issue ?
<img width="175" alt="Screenshot 2021-03-16 at 08 02 14" src="https://user-images.githubusercontent.com/3224216/111275659-49d14080-862e-11eb-9bfb-931ba565940b.png">
![1](https://user-images.githubusercontent.com/3224216/111275763-640b1e80-862e-11eb-9ce5-de9738388d4a.png)

**Comment by SchalkCloete** [comment]
My view looks like this:
![image](https://user-images.githubusercontent.com/69623855/111279279-d3870b00-863a-11eb-8dab-40b2565e213b.png)

Also, in the ones you posted above, the bio is either being obscured by another profile or overlapping with another profile. This looks rather messy. What is usually done in these cases is that a long message is truncated after a certain number of characters followed by three dots (...) indicating that more text can be viewed when clicking on the item. That was what I was suggesting.

**Comment by blamarque** [comment]
Hey there, please make sure you are on the latest version 0.27.* - you should have the latest effect then.

The bio does not obscured an other one, as it overlap on top only when moved over.

**Comment by SchalkCloete** [comment]
Yes, I have 0.27.1. I see that the text now disappears behind any other profile that lies beneath it, but it still doesn't look neat, especially if there is no box below it and the text just extends out of the box into the white space below. 

But this is not a critical priority - just a cosmetic thing. I suggest reopening this ticket and postponing it for later to implement the automatic truncation of text after a certain number of characters as outlined above.
