### ISSUE TITLE
Warning to Gmail users that the sign-up link must be manually copied to their mobile browser to give them permanent access

### ISSUE THREAD

**Issue by SchalkCloete** [MyResonance/tickets#33]
This caused plenty of frustration because Gmail opens the sign-up link in the Gmail app itself and not in the phone's browser. Hence, trying to access MyResonance on the browser repeatedly asks for new sign-ups. To get around this, the link either has to be manually copied to the phone's browser, or the Gmail setting to open webpages in the app must be deactivated.

**Comment by blamarque** [comment]
I am thinking adding something in the magic link email along the line 
```Or copy and paste the link above into your browser.```

**Comment by SchalkCloete** [comment]
OK, cool. Perhaps just mention the Gmail mobile app in brackets. Maybe something like this:
"Or copy and paste the link above into your browser (recommended for Gmail mobile app users)."

**Comment by SchalkCloete** [comment]
Hmm... I see this huge link is now in every mail about a new activity being registered. I think it's only needed in the first mail after signup.

**Comment by blamarque** [comment]
Better be save :)

**Comment by SchalkCloete** [comment]
OK :-)
