### ISSUE TITLE
More clarity about Strava use in the Fitness challenge

### ISSUE THREAD

**Issue by SchalkCloete** [MyResonance/tickets#40]
The Strava mobile app does not allow recording of activities that do not involve GPS, so this can be confusing to users. Please add a clarification to the instructions that people should record "walking" on Strava and then change it to whatever fitness activity they actually did in the process of saving the activity on the Strava app.

**Comment by blamarque** [comment]
Actually this will be an issue for MyResonance - as we will received the Walk event from strava and not the update.

The way I am doing it, is using my watch and doing "other activity" - without GPS.
Strava convert it automatically to fitness - which then fit MyResonance activity mapping.

With the strava app, I guess the best solution is to declare the activity manually.

**Comment by SchalkCloete** [comment]
The mobile app allows you to change the activity before saving it. Both my mom and I have done it now a few times for yoga and it works well. Here are some simple instructions to help users:

"If you use the Strava mobile app, activities without GPS tracking cannot be recorded directly. As a workaround, simply record walking (or anything else). When you're done, stop and finish the activity. On the next screen, you can correct the type of activity before saving. If you have a fitness watch linked to Strava, you may be able to record non-GPS activities directly."

**Comment by blamarque** [comment]
Can we add that in the FAQ instead? I don t see where we can make it fit in the app.

**Comment by SchalkCloete** [comment]
OK, it is a bit long. Maybe you can modify the following point in the "How it works" section:

- Use Strava to automatically share your efforts (see the FAQ for some handy tips)

I'll move the text as a new comment to #23
