### ISSUE TITLE
Strava integration procedure can be better formulated

### ISSUE THREAD

**Issue by SchalkCloete** [MyResonance/tickets#42]
After signing up for a team, the next box says something about integrating Strava that will automatically pop up after the pledge is made. Then there is a small Strava button and a large complete button. These are rather confusing instructions because the best is to actually click on the small Strava button and complete the integration. 

Please make these instructions clearer by saying directly that users should click on the small Strava button to link their account if it is not linked yet through another challenge.

**Comment by blamarque** [comment]
I am thinking that perhaps the best is to have "Connect with X" on top of the feed (where the timer button is in the push up challenge) to indicate that no system is connected yet.

**Comment by SchalkCloete** [comment]
OK, that should work too, as long as the button is only visible when Strava is not yet connected.

**Comment by blamarque** [comment]
Done

**Comment by SchalkCloete** [comment]
If I understand correctly, this fix is supposed to prevent the new issue I opened in #78, but it seems like it is not working because I could not see any login button at the top of the feed for the new test user I created, neither on mobile or desktop.

**Comment by blamarque** [comment]
Looking at it

**Comment by blamarque** [comment]
fixed

**Comment by SchalkCloete** [comment]
Nice! I can see the button now, but there's no text like "Connet to Strava" on it.

**Comment by blamarque** [comment]
I think the lang file were still deploying. Should be ok
