### ISSUE TITLE
The edit post page reached when clicking on the email link on mobile is still in the desktop format

### ISSUE THREAD

**Issue by SchalkCloete** [MyResonance/tickets#50]
This is a page that users will visit quite often to upload photos after an activity, so it should look good. 

Maybe fixing the layout to the mobile version will also fix issue #5 that the edit post window extends out of the screen.

**Comment by SchalkCloete** [comment]
Thanks, but I checked now on some older email invites to edit my activities, and the problem is that the "edit" button is now missing on mobile. This is quite a serious issue that should be fixed soon (linked to issue #51).

**Comment by blamarque** [comment]
Yes the edit for mobile is in progress #51
