### ISSUE TITLE
Edit, star, and promote buttons are missing in the mobile version

### ISSUE THREAD

**Issue by SchalkCloete** [MyResonance/tickets#51]
It would be useful to have these functionalities also on mobile.

**Comment by SchalkCloete** [comment]
Ah, thanks! That was quick :-) However, I found two small issues that remain: 1) the image button in the edit post box doesn't seem to work (nothing happens when I tap it to add an image) and 2) although all the buttons are visible when scrolling through the posts in the different challenges, the edit, promote, and star buttons are missing when following the email link received after completing a Strava activity.

**Comment by blamarque** [comment]
That should be all fine now.
Please try and let me know

**Comment by SchalkCloete** [comment]
Thanks, that's better, yes! One small bug is that the cancel button on the camera option doesn't work. Also, for the Active challenge, it's important to be able to add pictures from the gallery (I added a comment to #66 about that).
