### ISSUE TITLE
Confusing instructions after changing a pledge in the Active and Fitness challenges

### ISSUE THREAD

**Issue by SchalkCloete** [MyResonance/tickets#70]
After changing a pledge in the Active of Fitness challenges, the confusing box with the Strava integration button comes up again, even after Strava is already connected. 

The text in the box says "Tracking your activity is easy via free app Strava which you'll be taken to when you hit pledge" Then there is a "strava" button and a "Done!" button. 

When adjusting the pledge, please change the text to: "Your pledge was adjusted successfully" and remove the "strava" button. 

When signing up for the first time, the current text can be adjusted to "Tracking your activity is easy via the free fitness tracker: Strava. You can link your account now using the button below. Otherwise, you can always link your account at a later stage."

**Comment by blamarque** [comment]
Ok text updated 

I have create  #71 for the flow adjustment of the pledge
