### ISSUE TITLE
Make more teams visible on mobile (or indicate more clearly that there are more teams when scrolling down)

### ISSUE THREAD

**Issue by SchalkCloete** [MyResonance/tickets#77]
When choosing a team, only the three first teams are visible and there is no instinctive indication that it is possible to scroll down to see more teams (I just scrolled down because I knew there were more teams). There is lots of space left on the screen to make all the teams visible to avoid any confusion here.

**Comment by blamarque** [comment]
Hello, 

I can t reproduce it - would it be possible to get a screenshot ?

Thanks

**Comment by SchalkCloete** [comment]
I've already signed up for all the challenges with the new user I created, but I tried now to change teams under the Team Stats page. However, if I do that, I get the "unexpected error occurred" message.
